{{- range $name, $app := .Values.applications }}
{{- if $app.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $app.name | default $name }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: {{ $.Values.gitRepository.url }}
    targetRevision: {{ $.Values.gitRepository.targetRevision }}
    path: {{ $app.path }}
    
    {{- if $app.helm }}
    helm:
      {{- if $app.helm.valueFiles }}
      valueFiles:
        {{- range $app.helm.valueFiles }}
        - {{ . }}
        {{- end }}
      {{- end }}
      
      {{- if $app.helm.values }}
      values: |
        {{- $app.helm.values | nindent 8 }}
      {{- end }}
      
      {{- if $app.helm.parameters }}
      parameters:
        {{- range $app.helm.parameters }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
      {{- end }}
    {{- end }}
  
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $app.namespace | default "default" }}
  
  syncPolicy:
    {{- if $app.syncPolicy.automated }}
    automated:
      prune: {{ $app.syncPolicy.automated.prune | default false }}
      selfHeal: {{ $app.syncPolicy.automated.selfHeal | default false }}
    {{- end }}
    
    {{- if $app.syncPolicy.syncOptions }}
    syncOptions:
      {{- range $app.syncPolicy.syncOptions }}
      - {{ . }}
      {{- end }}
    {{- end }}
    
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
{{- end }}
{{- end }}