apiVersion: v2
name: django-app
description: A Helm chart for Django applications
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - django
  - python
  - web
  - application
home: https://www.djangoproject.com/
sources:
  - https://github.com/django/django
maintainers:
  - name: DevOps Team
    email: devops@company.com
annotations:
  category: Web Applications
  licenses: MIT