# Default values for django-app
replicaCount: 2

image:
  repository: ""  # Will be set to ECR repository URL
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

ingress:
  enabled: false
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  host: "yourdomain.com"
  path: "/"
  pathType: "Prefix"
  tls: true

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Environment variables from ConfigMap
env:
  DJANGO_SECRET: "django-insecure-hxa(3%^t*$*f*nk7yg*^$wj9f-72mu1i1heg(3m4!da4y@#_mc"
  POSTGRES_DB: "mydb"
  POSTGRES_USER: "myuser"
  POSTGRES_PASSWORD: "mypassword"
  POSTGRES_HOST: "db"
  POSTGRES_PORT: "5432"
  DEBUG: "True"
  ALLOWED_HOSTS: "localhost,127.0.0.1,0.0.0.0"