version: "3.9"

services:
  web:
    build: .
    container_name: django_app
    env_file: .env
    environment:
      DJANGO_SECRET: ${DJANGO_SECRET}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - ./app:/app
    depends_on:
      - db
    ports:
      - "8000:8000"   # можна відкрити напряму, nginx працюватиме на 80

  db:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"

volumes:
  postgres_data:
